### ISSUE TITLE
Mistake regarding PEP 563 in Python 3.11

### ISSUE THREAD

**Issue by vbrozik** [jugmac00/python-version-cheat-sheet#7]
> python 3.11
> postponed evaluation of type annotations, that means from __future__ import annotations is no longer necessary ([PEP 563](https://www.python.org/dev/peps/pep-0563/))

The change is in fact very different: PEP 563 may never be implemented.

> PEP 563 may not be the future
> [PEP 563](https://peps.python.org/pep-0563/) Postponed Evaluation of Annotations (the from __future__ import annotations [future statement](https://docs.python.org/3/reference/simple_stmts.html#future)) that was originally planned for release in Python 3.10 has been put on hold indefinitely. See [this message from the Steering Council](https://mail.python.org/archives/list/python-dev@python.org/message/VIZEBX5EYMSYIJNDBF6DMUMZOCWHARSO/) for more information.

https://docs.python.org/3/whatsnew/3.11.html#pep-563-may-not-be-the-future

**Comment by jugmac00** [comment]
Thank you very much! I was not aware of this update!
